# Generated by Django 5.2.5 on 2025-08-08 15:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('email', models.EmailField(max_length=254, verbose_name='メールアドレス')),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='電話番号は数字とハイフンのみ入力可能です。', regex='^[0-9\\-]+$')], verbose_name='電話番号')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='サービス名')),
                ('duration_minutes', models.IntegerField(verbose_name='時間（分）')),
                ('price', models.IntegerField(verbose_name='料金')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'サービス',
                'verbose_name_plural': 'サービス',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], verbose_name='曜日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('is_available', models.BooleanField(default=True, verbose_name='予約可能')),
            ],
            options={
                'verbose_name': '営業時間',
                'verbose_name_plural': '営業時間',
                'unique_together': {('weekday', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='予約日')),
                ('booking_time', models.TimeField(verbose_name='予約時間')),
                ('status', models.CharField(choices=[('pending', '予約申込中'), ('confirmed', '予約確定'), ('completed', '施術完了'), ('cancelled', 'キャンセル'), ('no_show', '無断キャンセル')], default='pending', max_length=20, verbose_name='ステータス')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.customer', verbose_name='顧客')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.service', verbose_name='サービス')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
                'unique_together': {('booking_date', 'booking_time')},
            },
        ),
    ]
