# Generated by Django 5.2.5 on 2025-08-09 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='お名前')),
                ('display_name', models.CharField(help_text='お客様に表示される名前', max_length=100, verbose_name='表示名')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='therapists/', verbose_name='写真')),
                ('introduction', models.TextField(blank=True, help_text='経歴や得意な施術など', verbose_name='自己紹介')),
                ('specialties', models.TextField(blank=True, help_text='専門分野や得意なマッサージ技術', verbose_name='得意な施術')),
                ('experience_years', models.IntegerField(default=0, verbose_name='経験年数')),
                ('is_active', models.BooleanField(default=True, help_text='予約受付中かどうか', verbose_name='有効')),
                ('is_featured', models.BooleanField(default=False, help_text='トップページで強調表示', verbose_name='おすすめ')),
                ('sort_order', models.IntegerField(default=0, help_text='小さい数字ほど上に表示', verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '施術者',
                'verbose_name_plural': '施術者',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.therapist', verbose_name='施術者'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('booking_date', 'booking_time', 'therapist')},
        ),
    ]
