# Generated by Django 5.2.5 on 2025-08-10 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_therapist_alter_booking_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_interval_minutes', models.IntegerField(default=30, help_text='予約可能な時間の間隔（例：30分ごと）', verbose_name='予約時間間隔（分）')),
                ('treatment_buffer_minutes', models.IntegerField(default=15, help_text='施術と施術の間の準備時間', verbose_name='施術間インターバル（分）')),
                ('advance_booking_days', models.IntegerField(default=90, help_text='何日先まで予約を受け付けるか', verbose_name='事前予約可能日数')),
                ('same_day_booking_cutoff', models.TimeField(default='12:00', help_text='当日予約の受付締切時間', verbose_name='当日予約締切時間')),
                ('default_treatment_duration', models.IntegerField(default=90, help_text='何も指定がない場合の施術時間', verbose_name='標準施術時間（分）')),
                ('allow_same_time_bookings', models.BooleanField(default=False, help_text='複数の施術者がいる場合、同じ時刻の予約を許可するか', verbose_name='同時刻複数予約許可')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '予約設定',
                'verbose_name_plural': '予約設定',
            },
        ),
        migrations.CreateModel(
            name='BusinessHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], unique=True, verbose_name='曜日')),
                ('is_open', models.BooleanField(default=True, verbose_name='営業日')),
                ('open_time', models.TimeField(default='09:00', verbose_name='開店時間')),
                ('close_time', models.TimeField(default='20:00', verbose_name='閉店時間')),
                ('last_booking_time', models.TimeField(default='19:00', help_text='この時間以降の予約は受け付けません', verbose_name='最終予約受付時間')),
            ],
            options={
                'verbose_name': '営業時間',
                'verbose_name_plural': '営業時間',
                'ordering': ['weekday'],
            },
        ),
        migrations.DeleteModel(
            name='TimeSlot',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='photo',
        ),
    ]
