# Generated by Django 5.2.5 on 2025-08-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookingsettings_businesshours_delete_timeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='enable_therapist_selection',
            field=models.BooleanField(default=True, help_text='お客様が施術者を指名できるかどうか（OFFにすると指名なしの選択肢が非表示になります）', verbose_name='施術者指名機能'),
        ),
    ]
