# Generated by Django 5.2.5 on 2025-08-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingsettings_enable_therapist_selection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='予定タイトル')),
                ('schedule_type', models.CharField(choices=[('break', '休憩'), ('meeting', '会議・打ち合わせ'), ('training', '研修・勉強'), ('maintenance', '設備メンテナンス'), ('preparation', '準備時間'), ('admin', '事務作業'), ('other', 'その他')], default='other', max_length=20, verbose_name='予定種別')),
                ('schedule_date', models.DateField(verbose_name='予定日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('description', models.TextField(blank=True, verbose_name='詳細・備考')),
                ('is_recurring', models.BooleanField(default=False, help_text='毎週同じ曜日・時間に繰り返す予定', verbose_name='繰り返し予定')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_by', models.CharField(default='管理者', max_length=100, verbose_name='作成者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('therapist', models.ForeignKey(blank=True, help_text='特定の施術者に関連する予定の場合', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.therapist', verbose_name='担当者')),
            ],
            options={
                'verbose_name': '予定',
                'verbose_name_plural': '予定',
                'ordering': ['schedule_date', 'start_time'],
            },
        ),
    ]
