# Generated by Django 5.2.5 on 2025-08-13 XX:XX

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_schedule'),
    ]

    operations = [
        # BookingSettingsに空白時間ブロック機能を追加
        migrations.AddField(
            model_name='bookingsettings',
            name='auto_block_gaps',
            field=models.BooleanField(default=True, help_text='短い空白時間を自動的に予約不可にする機能を有効にする', verbose_name='空白時間の自動ブロック'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='minimum_gap_minutes',
            field=models.PositiveIntegerField(default=90, help_text='この時間以下の空白は自動的に予約不可になります（30-300分）', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)], verbose_name='最小空白時間（分）'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='gap_block_before_opening',
            field=models.BooleanField(default=True, help_text='営業開始から最初の予約までの空白時間もブロック対象にする', verbose_name='営業開始前の空白もブロック'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='gap_block_after_closing',
            field=models.BooleanField(default=True, help_text='最後の予約から営業終了までの空白時間もブロック対象にする', verbose_name='営業終了後の空白もブロック'),
        ),
        migrations.AddField(
            model_name='bookingsettings',
            name='gap_block_between_bookings',
            field=models.BooleanField(default=True, help_text='予約と予約の間の空白時間をブロック対象にする', verbose_name='予約間の空白をブロック'),
        ),
        
        # GapBlockモデルを作成
        migrations.CreateModel(
            name='GapBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_date', models.DateField(verbose_name='ブロック日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('block_type', models.CharField(choices=[('before_opening', '営業開始前'), ('between_bookings', '予約間'), ('after_closing', '営業終了前'), ('manual', '手動設定')], max_length=20, verbose_name='ブロック種別')),
                ('reason', models.CharField(max_length=200, verbose_name='理由')),
                ('is_auto_generated', models.BooleanField(default=True, verbose_name='自動生成')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('therapist', models.ForeignKey(blank=True, help_text='特定の施術者のブロック（空白の場合は全体）', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.therapist', verbose_name='対象施術者')),
            ],
            options={
                'verbose_name': '空白時間ブロック',
                'verbose_name_plural': '空白時間ブロック',
                'ordering': ['-block_date', 'start_time'],
            },
        ),
        
        # インデックスを追加
        migrations.AddIndex(
            model_name='gapblock',
            index=models.Index(fields=['block_date', 'therapist'], name='bookings_gapblock_date_therapist_idx'),
        ),
        migrations.AddIndex(
            model_name='gapblock',
            index=models.Index(fields=['is_active', 'is_auto_generated'], name='bookings_gapblock_active_auto_idx'),
        ),
    ]