# Generated by Django 5.2.5 on 2025-08-13 13:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_add_gap_blocking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_date', '-booking_time'], 'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['-created_at'], 'verbose_name': '顧客', 'verbose_name_plural': '顧客'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-schedule_date', 'start_time'], 'verbose_name': '予定', 'verbose_name_plural': '予定'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'サービス', 'verbose_name_plural': 'サービス'},
        ),
        migrations.RenameIndex(
            model_name='gapblock',
            new_name='bookings_ga_block_d_1513e0_idx',
            old_name='bookings_gapblock_date_therapist_idx',
        ),
        migrations.RenameIndex(
            model_name='gapblock',
            new_name='bookings_ga_is_acti_e7edbc_idx',
            old_name='bookings_gapblock_active_auto_idx',
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='specialties',
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='service',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='description',
            field=models.TextField(blank=True, verbose_name='紹介文'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='therapists/', verbose_name='写真'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', '承認待ち'), ('confirmed', '確定'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='pending', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.therapist', verbose_name='施術者'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='advance_booking_days',
            field=models.PositiveIntegerField(default=90, help_text='何日先まで予約を受け付けるか（1-365日）', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='予約受付期間（日）'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='allow_same_time_bookings',
            field=models.BooleanField(default=False, help_text='複数の施術者が同じ時間に予約を取れるかどうか', verbose_name='同時刻予約許可'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='booking_interval_minutes',
            field=models.PositiveIntegerField(default=10, help_text='予約時間の間隔を分単位で設定（5-60分）', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)], verbose_name='予約間隔（分）'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='default_treatment_duration',
            field=models.PositiveIntegerField(default=90, help_text='新規サービス作成時のデフォルト時間（30-300分）', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)], verbose_name='デフォルト施術時間（分）'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='same_day_booking_cutoff',
            field=models.TimeField(default='12:00', help_text='この時間以降は当日予約を受け付けない', verbose_name='当日予約締切時間'),
        ),
        migrations.AlterField(
            model_name='bookingsettings',
            name='treatment_buffer_minutes',
            field=models.PositiveIntegerField(default=15, help_text='施術と施術の間の休憩時間（0-60分）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='施術間インターバル（分）'),
        ),
        migrations.AlterField(
            model_name='businesshours',
            name='last_booking_time',
            field=models.TimeField(default='19:00', verbose_name='最終予約受付時間'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_by',
            field=models.CharField(default='system', max_length=100, verbose_name='作成者'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='繰り返し予定'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_type',
            field=models.CharField(choices=[('break', '休憩'), ('meeting', '会議・打ち合わせ'), ('training', '研修・勉強'), ('maintenance', 'メンテナンス'), ('preparation', '準備・片付け'), ('admin', '事務作業'), ('other', 'その他')], max_length=20, verbose_name='予定種別'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='therapist',
            field=models.ForeignKey(blank=True, help_text='特定の施術者に関連する予定の場合のみ選択', null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.therapist', verbose_name='担当者'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(verbose_name='施術時間（分）'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.PositiveIntegerField(verbose_name='料金'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='display_name',
            field=models.CharField(help_text='お客様に表示される名前', max_length=50, verbose_name='表示名'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='name',
            field=models.CharField(max_length=50, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='表示順'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('therapist', 'booking_date', 'booking_time')},
        ),
    ]
