# Generated by Django 5.2.5 on 2025-08-16 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_alter_booking_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingsettings',
            name='min_advance_minutes',
            field=models.PositiveIntegerField(default=20, help_text='予約は何分前まで受け付けるか（5-120分）※当日のみ適用', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(120)], verbose_name='直前予約制限時間（分）'),
        ),
    ]
