# Generated by Django 5.2.5 on 2025-08-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_bookingsettings_min_advance_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='メンテナンスモード')),
                ('message', models.TextField(default='メンテナンス中です。予約希望の方は下記までご連絡ください。', help_text='メンテナンス画面に表示されるメッセージ', verbose_name='メンテナンスメッセージ')),
                ('contact_email', models.EmailField(default='info@gracespa.com', help_text='メンテナンス中の連絡先として表示されるメールアドレス', max_length=254, verbose_name='連絡先メールアドレス')),
                ('contact_phone', models.CharField(default='03-1234-5678', help_text='メンテナンス中の連絡先として表示される電話番号', max_length=20, verbose_name='連絡先電話番号')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='開始日時')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='終了予定日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'メンテナンスモード',
                'verbose_name_plural': 'メンテナンスモード',
            },
        ),
    ]
