# Generated by Django 5.2.5 on 2025-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_maintenancemode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(
                blank=True, 
                choices=[('male', '男性'), ('female', '女性')], 
                max_length=10, 
                null=True, 
                verbose_name='性別'
            ),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_first_visit',
            field=models.BooleanField(
                default=True, 
                help_text='初回利用かどうか', 
                verbose_name='初回利用'
            ),
        ),
    ]