# Generated by Django 5.2.5 on 2025-08-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_add_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='説明（英語）'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='サービス名（英語）'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='紹介文（英語）'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='display_name_en',
            field=models.CharField(blank=True, default='', help_text='英語版で表示される名前', max_length=50, verbose_name='表示名（英語）'),
        ),
    ]
