# Generated by Django 5.2.5 on 2025-08-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_add_customer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer_gender',
            field=models.CharField(
                blank=True, 
                choices=[('male', '男性'), ('female', '女性')], 
                max_length=10, 
                null=True, 
                verbose_name='予約時の性別選択'
            ),
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_is_first_visit',
            field=models.BooleanField(
                default=False, 
                verbose_name='予約時の初回利用選択'
            ),
        ),
    ]